name: sic_app
description: Sistema de Contabilidad Iglesia - SIC App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.4.0

  go_router: ^14.2.0

  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  fl_chart: ^0.68.0

  pdf: ^3.11.0
  printing: ^5.13.0
  share_plus: ^10.0.0

  intl: ^0.19.0
  uuid: ^4.4.0
  equatable: ^2.0.5
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10
  image_picker: ^1.2.1
  firebase_storage: ^12.4.10
  firebase_messaging: ^15.2.10
<<<<<<< HEAD
=======
  rxdart: ^0.28.0
>>>>>>> origin/ulises

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  riverpod_generator: ^2.4.3
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - lib/core/assets/LogoFinTrack.png
    - lib/core/assets/logotipo.png

flutter_native_splash:
  color: "#FFFFFF" # fondo blanco
  image: lib/core/assets/LogoFinTrack.png
  android: true
  ios: true
  web: false
  android_gravity: center
  ios_content_mode: scaleAspectFit

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/core/assets/LogoFinTrack.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"  # color de fondo blanco
  adaptive_icon_foreground: "lib/core/assets/LogoFinTrack.png"