// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJZF_LRtM5whCevuzZGt1gFzoIp8yvyWI',
    appId: '1:496479402543:web:113fcae128c0407f26e4da',
    messagingSenderId: '496479402543',
    projectId: 'fintrack-66558',
    authDomain: 'fintrack-66558.firebaseapp.com',
    databaseURL: 'https://fintrack-66558-default-rtdb.firebaseio.com',
    storageBucket: 'fintrack-66558.firebasestorage.app',
    measurementId: 'G-TYLMH4RELV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4Ba1mJXv_PIfWMckqbywXUpSquFurlUg',
    appId: '1:496479402543:android:3abdfa3c86082cb126e4da',
    messagingSenderId: '496479402543',
    projectId: 'fintrack-66558',
    databaseURL: 'https://fintrack-66558-default-rtdb.firebaseio.com',
    storageBucket: 'fintrack-66558.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAelUgfx0BAF14io0C_m-rwma-3Kd6Cfd8',
    appId: '1:496479402543:ios:0cfe1a310276aff526e4da',
    messagingSenderId: '496479402543',
    projectId: 'fintrack-66558',
    databaseURL: 'https://fintrack-66558-default-rtdb.firebaseio.com',
    storageBucket: 'fintrack-66558.firebasestorage.app',
    iosClientId: '496479402543-9a3tqfr95fsf6mlujo0e5ilr64s9990r.apps.googleusercontent.com',
    iosBundleId: 'com.example.fintrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAelUgfx0BAF14io0C_m-rwma-3Kd6Cfd8',
    appId: '1:496479402543:ios:0cfe1a310276aff526e4da',
    messagingSenderId: '496479402543',
    projectId: 'fintrack-66558',
    databaseURL: 'https://fintrack-66558-default-rtdb.firebaseio.com',
    storageBucket: 'fintrack-66558.firebasestorage.app',
    iosClientId: '496479402543-9a3tqfr95fsf6mlujo0e5ilr64s9990r.apps.googleusercontent.com',
    iosBundleId: 'com.example.fintrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJZF_LRtM5whCevuzZGt1gFzoIp8yvyWI',
    appId: '1:496479402543:web:32cde1d780ac777526e4da',
    messagingSenderId: '496479402543',
    projectId: 'fintrack-66558',
    authDomain: 'fintrack-66558.firebaseapp.com',
    databaseURL: 'https://fintrack-66558-default-rtdb.firebaseio.com',
    storageBucket: 'fintrack-66558.firebasestorage.app',
    measurementId: 'G-NPFCJ3Z0FC',
  );
}
